name: CI

on: 
  pull_request:
    branches:
    - develop

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@master
    - name: update Algolia with GA Pageviews
      env: 
        GOOGLE_ALGOLIA_CREDENTIALS: ${{secrets.GOOGLE_ALGOLIA_CREDENTIALS}}
      run: |
        GOOGLE_ALGOLIA_CREDENTIALS node -p -e 'const {type,private_key_id,private_key,project_id,client_email,client_id,auth_uri,token_uri,auth_provider_x509_cert_url,client_x509_cert_url} = process.env; require("fs").writeFile("auth.json", JSON.stringify({type,project_id,private_key_id,private_key:private_key.replace(/\\n/g,"\n"),client_email,client_id,auth_uri,token_uri,auth_provider_x509_cert_url,client_x509_cert_url},null,2), err=>{})'

        GOOGLE_APPLICATION_CREDENTIALS=auth.json node ga_connector.js;
        rm -rf auth.json

    - name: lint all markdownfiles
      run: |
        npm install
        node_modules/.bin/markdownlint ./ --ignore node_modules --ignore legacy-documentation
    - name: check for image url
      run: |
        if grep -lri 's3.amazonaws.com/postman-static-getpostman-com' ./src/pages/docs ; 
        then echo "Invalid s3 references found. Please use format 'https://assets.postman.com/postman-docs/[filename-in-s3]'"; 
          exit 1; 
        else echo "no s3 references found"; 
        fi
    - name: running unit tests
      run: |
        npm install
        npm run clean
        npm run test:update
    
